title: Exploring Localization with Melody 
description: Come aboard and let's navigate this exciting world together!
show_downloads: False
google_analytics:
theme: jekyll-theme-cayman

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
